"""Bring up the graphics session: seatd, then the compositor, then the page.

The container carries its own compositor because the devices this runs on
generally have none — no X, no Wayland, often no GPU userspace at all. sway is
used rather than a smaller kiosk compositor purely because it is the one that
can pin an output mode, which is what lets a 1080p panel be driven at 720p to
save a software renderer a lot of work.
"""

from __future__ import annotations

import asyncio
import logging
import os
import shutil
import signal
from pathlib import Path

from .display import Display, Mode

log = logging.getLogger(__name__)

RUNTIME_DIR = Path("/tmp/kiosk-runtime")
CONFIG_PATH = RUNTIME_DIR / "sway.conf"

ROTATIONS = {0: "normal", 90: "90", 180: "180", 270: "270"}


def build_sway_config(
    display: Display,
    mode: Mode | None,
    rotation: int,
    hide_cursor: bool,
    browser_command: str,
) -> str:
    """A compositor config with exactly one job."""
    output_line = f"output {display.connector}"
    if mode:
        output_line += f" mode {mode}"
    output_line += f" transform {ROTATIONS.get(rotation, 'normal')} position 0 0"

    return "\n".join(
        [
            "# Generated by the Doover kiosk-display app. Edits will be overwritten.",
            output_line,
            # No X11 clients here, and without this sway logs a failure to
            # start Xwayland on every boot — noise in a support log.
            "xwayland disable",
            # Anything not covered by the page is black rather than undefined.
            f"output {display.connector} bg #000000 solid_color",
            "default_border none",
            "default_floating_border none",
            "hide_edge_borders --i3 both",
            "focus_follows_mouse no",
            *(["seat * hide_cursor 1"] if hide_cursor else []),
            # Anything the browser opens is still the kiosk; keep it fullscreen.
            'for_window [app_id=".*"] fullscreen enable',
            f"exec_always {browser_command}",
            "",
        ]
    )


def session_environment(display: Display, force_renderer: str = "auto") -> dict[str, str]:
    """Environment for the compositor and everything it launches.

    The renderer decision is the important one. wlroots' pixman renderer draws
    on the CPU into dumb buffers and needs no GPU userspace at all, which is the
    only thing that works on a board whose GPU has a vendor-only driver.
    """
    accelerated = display.accelerated
    if force_renderer == "gl":
        accelerated = True
    elif force_renderer == "pixman":
        accelerated = False

    env = {
        **os.environ,
        "WLR_BACKENDS": "drm",
        "WLR_DRM_DEVICES": display.device,
        "LIBSEAT_BACKEND": "seatd",
        "XDG_RUNTIME_DIR": str(RUNTIME_DIR),
        "GDK_BACKEND": "wayland",
        # WebKit's sandbox needs a user namespace the container may not grant.
        "WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS": "1",
    }

    if not accelerated:
        env["WLR_RENDERER"] = "pixman"
        env["LIBGL_ALWAYS_SOFTWARE"] = "1"
        env["GALLIUM_DRIVER"] = "llvmpipe"
    if display.dri_path:
        env["LIBGL_DRIVERS_PATH"] = display.dri_path

    return env


async def stop_conflicting_services(names: list[str]) -> list[str]:
    """Stop whatever else is drawing on the panel.

    Some vendor images run their own status screen on the framebuffer — ELPRO's
    Quantum ships two copies of a Qt splash — and it will happily repaint over
    anything this app draws. The host's init directory is bind-mounted in so the
    scripts can be stopped from here; disabling them at boot is left to the
    operator, because it is their device's behaviour being changed.
    """
    stopped = []
    for name in names:
        name = name.strip()
        if not name:
            continue
        script = Path("/host/etc/init.d") / name
        if not script.exists():
            log.info("Conflicting service %r not present; nothing to stop", name)
            continue
        try:
            proc = await asyncio.create_subprocess_exec(
                str(script), "stop",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
            await asyncio.wait_for(proc.communicate(), timeout=15)
            log.info("Stopped conflicting service %r", name)
            stopped.append(name)
        except (OSError, asyncio.TimeoutError) as exc:
            log.warning("Could not stop %r: %s", name, exc)
    return stopped


class Session:
    """Owns the seatd and sway processes for the life of the app."""

    def __init__(self) -> None:
        self.seatd: asyncio.subprocess.Process | None = None
        self.sway: asyncio.subprocess.Process | None = None

    @property
    def running(self) -> bool:
        return self.sway is not None and self.sway.returncode is None

    async def start(self, config: str, env: dict[str, str]) -> None:
        RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
        RUNTIME_DIR.chmod(0o700)
        CONFIG_PATH.write_text(config)
        log.info("Compositor config:\n%s", config)

        if shutil.which("seatd") is None or shutil.which("sway") is None:
            raise RuntimeError("seatd and sway must be installed in the image")

        self.seatd = await asyncio.create_subprocess_exec(
            "seatd", stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL
        )
        # seatd has to own its socket before wlroots asks for a seat.
        await asyncio.sleep(2)

        # Inherit stdio rather than piping it. A pipe nothing drains fills its
        # buffer and then blocks the compositor — and the browser logs through
        # the same stream, so it would take the display down with it. Inheriting
        # puts both in `docker logs` where they are actually useful.
        self.sway = await asyncio.create_subprocess_exec(
            "sway", "-c", str(CONFIG_PATH),
            env=env,
        )
        log.info("Started compositor (pid %s)", self.sway.pid)

    async def stop(self) -> None:
        for proc, name in ((self.sway, "sway"), (self.seatd, "seatd")):
            if proc is None or proc.returncode is not None:
                continue
            try:
                proc.send_signal(signal.SIGTERM)
                await asyncio.wait_for(proc.wait(), timeout=10)
            except (asyncio.TimeoutError, ProcessLookupError):
                log.warning("%s did not exit; killing", name)
                try:
                    proc.kill()
                except ProcessLookupError:
                    pass
        self.sway = self.seatd = None
